services:
  node:
    container_name: pwa_vue
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/app
    command: sh -c "cd pwa_vue && npm run serve"
    ports:
    - "8080:8080"
